### ISSUE TITLE
Doesn't work on Ubuntu 9.10

### ISSUE THREAD

**Issue by cmahnke** [entrope/linux-magicmouse#1]
Kernel:
uname -a
Linux cmahnke-laptop 2.6.31-18-generic #55-Ubuntu SMP Fri Jan 8 14:55:26 UTC 2010 i686 GNU/Linux

Output of dmesg (truncated):
Feb  1 23:39:30 localhost kernel: [  116.258554] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
Feb  1 23:39:30 localhost kernel: [  116.402896] magicmouse 0005:05AC:030D.0001: magicmouse hid parse failed
Feb  1 23:39:30 localhost kernel: [  116.402912] magicmouse: probe of 0005:05AC:030D.0001 failed with error -14

Or is it a mistake to use blueman-applet to configure the device? It tells me the it's connected but the mouse isn't working...

**Comment by entrope** [comment]
If you disconnect the mouse, it will work the second time you try to connect.  This appears to be a bug elsewhere in the kernel -- http://marc.info/?l=linux-bluetooth&m=126415822818922&w=2 has some analysis (which doesn't match what a backtrace shows on my system) and a patch (which doesn't work).  The only clear thing is that the kernel's hidp_connadd_req structure is being overwritten somewhere.

**Comment by entrope** [comment]
After further investigation, this is a bug in the Bluetooth hidp module when the device-specific driver module is not already loaded.  You can work around the bug by loading the hid-magicmouse module before you try to connect to the device.

**Comment by cmahnke** [comment]
Great thanks.
One can fix this by adding the following line to /etc/modules:
hid-magicmouse
