### ISSUE TITLE
Inconsistent scroll speed

### ISSUE THREAD

**Issue by thenozzl3** [entrope/linux-magicmouse#5]
thanx for your effort - quick issue/question about vertical scroll tuning - how can i get the speed to be more consistent ? It seems that some times the mouse only scrolls a few lines but as i keep scrolling the speed seems to ramp up (esp. when I scroll towards the top of the touch screen area or diagonally) ...

**Comment by entrope** [comment]
There is intentional acceleration as you keep scrolling.  You can change the acceleration rate by editing the values inside the "accel_profile" array.
